# Generated by Django 4.1.6 on 2023-06-05 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("litreview_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="time_created",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(
                    2023, 6, 5, 16, 47, 36, 156622, tzinfo=datetime.timezone.utc
                ),
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="ticket",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="tickets/"),
        ),
    ]
